<a href="https://colab.research.google.com/github/mrksntndr/Linear-Algebra-58019/blob/main/Eigenvalue_and_Eigenvector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np #To import Library
from numpy.linalg import eig

A = np.array([[-12,3],[4,1]]) #Making 2x2 Matrix (Named A)
print(A) #Displays A Matrix

inv_A = np.linalg.inv(A) #Inverse all the values of Matrix A
print(inv_A) #Displays the iversed output of Matrix A

B = np.array([[0],[0]]) #CMaking 2x2 Matrix (Named B)
print(B) #Displays B Matrix

X = np.dot(inv_A,B) #Dot product of the inverse of matrix A and matrix B
print(X) #Displays the dot product #X = solve(A,B) #print(X)

[[-12   3]
 [  4   1]]
[[-0.04166667  0.125     ]
 [ 0.16666667  0.5       ]]
[[0]
 [0]]
[[0.]
 [0.]]


In [6]:
A = np.array([[-6,3],[4,5]]) #Making 2x2 Matrix (Named A)
print(A) #Displays A Matrix

w,v = np.linalg.eig(A)
#Displays the output
print("The eigenvalue/s is/are:",w)
print("The right eigenvectors are:",v)
#x = v.round()
#print(x)

[[-6  3]
 [ 4  5]]
The eigenvalue/s is/are: [-7.  6.]
The right eigenvectors are: [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


In [4]:
A = np.array([[2,2,4],[1,3,5],[2,3,4]]) #Making 3x3 Matrix (Named A)
print(A) #Displays A Matrix
s,t = np.linalg.eig(A)
print(s.round())
print(t.round())
#Computes the eigenvalues and right eigenvectors of a square array
c = np.dot(A,t.round()) #dot product of A and t
print(c) #Displays the final output

[[2 2 4]
 [1 3 5]
 [2 3 4]]
[ 9.  1. -1.]
[[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]]
[[-8.  0.  2.]
 [-9.  2.  2.]
 [-9.  1.  1.]]
