<a href="https://colab.research.google.com/github/mrksntndr/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)

In [59]:
import numpy as np

N1 = np.array([[1,1,1], [1,0,4], [0,0,5]])
N2 = np.array([[89], [89], [95]])
T = np.linalg.inv(N1).dot(N2)

print(T)

[[13.]
 [57.]
 [19.]]


Problem 2. Solve each system: (30 points)

In [58]:
#Three linear equations with x, y, and z are unknown
#3x-y+z=5
#9x-3y+3z=15
#-12x+4y-4z=-20

A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]]) #create 3x3 matrix
print("Coefficients:") 
print(A) #print Coefficients

B = np.array([[5],[15],[-20]])
print("\nConstants:")
print(B) #print Constants

X = np.linalg.pinv(A) @ B # compute the pseudo inverse of A
                         
print("\nOutput:")
print(X) #print Outpout


Coefficients:
[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]

Constants:
[[  5]
 [ 15]
 [-20]]

Output:
[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


Problem 3. Consider the matrix, (40 points)

In [50]:
A = np.array([[8, 5, -6], [-12, -9, 12], [-3, -3, 5]]) #create 3x3 matrix

output, vector = np.linalg.eig(A) #application of eig method to obtain the eigen value and eigenvector 
print(f'\nEigenvalue(s): {output}') #print eigenvalue(s)
print(f'\nEigenvector(s):\n {vector}') #print eigenvector(s)
print(f'\nEigenvector(s):\n {vector.round()}')


Eigenvalue(s): [-1.  3.  2.]

Eigenvector(s):
 [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]

Eigenvector(s):
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
