<a href="https://colab.research.google.com/github/mrksntndr/Linear-Algebra-58019/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Python program to inverse

In [34]:
import numpy as np
A=np.array([[1,2],[4,7]])
invA=(np.linalg.inv(A))
print(invA)

[[-7.  2.]
 [ 4. -1.]]


In [35]:
C=np.dot(A,invA)
print(C)

[[1. 0.]
 [0. 1.]]


In [55]:
##Python Program to Transpose a 3x3 Matrix A=([[6,1,1],[4,-2,5],[2,8,7]])

A = np.array ([[6,1,1],[4,-2,5],[2,8,7]])

InvOfA = np.linalg.inv(A) #To inverse Matrix A

print(A)

B = np.transpose(A) #To transpose Matrix A

print (B)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


In [56]:

dot = np.dot(A, InvOfA) #Get dot product of A and its inverse

print(dot)

[[ 1.00000000e+00  0.00000000e+00  2.77555756e-17]
 [-1.38777878e-17  1.00000000e+00  1.38777878e-17]
 [-4.16333634e-17  1.38777878e-16  1.00000000e+00]]


##CODING ACTIVITY 3

In [57]:
A = np.array([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]])

InvOfA = np.linalg.inv(A) #To inverse Matrix A

print(A)

B = np.transpose(A) #To transpose Matrix A

print (B)

[[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]
[[ 6  4  2  3]
 [ 1 -2  8  1]
 [ 1  5  7  9]
 [ 3  1  6  7]]
