<a href="https://colab.research.google.com/github/mrksntndr/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

In [11]:
import numpy as np
#Sets the size of the matrix
size = (4,4)
#Creates a square matrix whose length is 4
square_matrix = np.zeros(size)
print('A square matrix with a length of 4')
print(square_matrix)

A square matrix with a length of 4
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Question 2


In [12]:
#Creates square matrix with elements below the principal diagonal are zero
square_matrix = np.array([[1,2,3,4,5],
                          [0,1,2,3,4],
                          [0,0,1,2,3],
                          [0,0,0,1,2],
                          [0,0,0,0,1]])

#Prints a square matrix whose elements below the principal diagonal are zero
print('A square matrix whose elements below the principal diagonal are zero')
print(square_matrix)

A square matrix whose elements below the principal diagonal are zero
[[1 2 3 4 5]
 [0 1 2 3 4]
 [0 0 1 2 3]
 [0 0 0 1 2]
 [0 0 0 0 1]]


Question 3


In [13]:
#Creates a square matrix  which is symmetrical
square_matrix = np.array([[1,2,3,4,5],
                          [2,1,2,3,4],
                          [3,2,1,2,3],
                          [4,3,2,1,2],
                          [5,4,3,2,1]])

#Prints a square matrix which is symmetrical
print('Square matrix that is symmetrical')
print(square_matrix)

A square matrix hich is symmetrical
[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


Question 4

In [4]:
C = np.array ([[1,2,3],[2,3,3],[3,4,-2]])
#Gets the inverse of Matrix C
invC = np.linalg.inv(C) #Inverse of Matrix C
print("The inverse of Matrix C:")
print(invC)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5

In [5]:
C = np.array ([[1,2,3],[2,3,3],[3,4,-2]])

detOfC = np.linalg.det(C)

print("The determinant of matrix in Question 4:")
print(int(detOfC))


Determinant of the given matrix in Question 4:
5


Question 6

In [15]:
eq = np.array([[5,4,1],
               [10,9,4],
               [10,13,15]])

const = np.array([[[3.4],
                   [8.8],
                   [19.2]]])

#Gets the root of the given linear equations
roots = np.linalg.inv(eq) @ const

#Prints the root of the given linear equations
print("The roots are")
print(roots)

The roots are
[[[0.2]
  [0.4]
  [0.8]]]
