<a href="https://colab.research.google.com/github/mrksntndr/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1

In [59]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]]) 
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2],[3,4]]) 

a = np.dot(A,B)
b = np.add(D,D)
c = 2*C

print("Problem 1.\n")
print("a)")
print(a)

print("\nb)")
print(b)

print("\nc)")
print(c)

Problem 1.

a)
[[22 28]
 [49 64]]

b)
[[2 4]
 [6 8]]

c)
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Problem 2

In [65]:
import numpy as np

θ = np.array ([5,3,-1])

print ("Problem 2.\n")
print ("Corresponding Matrix Representing:\nθ=5x+3y-z\n")
print (θ)

print ("\n\nDimension:")
print (θ.ndim)

print ("\nShape:")
print (θ.shape)

print ("\nSize")
print (θ.size)

print ("\nType")
print (type(θ))

Problem 2.

Corresponding Matrix Representing:
θ=5x+3y-z

[ 5  3 -1]


Dimension:
1

Shape:
(3,)

Size
3

Type
<class 'numpy.ndarray'>
