<a href="https://colab.research.google.com/github/mrksntndr/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
A = np.array([[-5,0],[4,1]]) 
B = np.array([[6,-3],[2,3]]) 

sum = np.add(A,B)
difference1 = np.subtract(A,B)
difference2 = np.subtract(B,A)

print("The sum of A and B:")
print(sum)
print("The difference of A and B:")
print(difference1)
print("The difference of B and A:")
print(difference2)

The sum of A and B:
[[ 1 -3]
 [ 6  4]]
The difference of A and B:
[[-11   3]
 [  2  -2]]
The difference of B and A:
[[11 -3]
 [-2  2]]
