<a href="https://colab.research.google.com/github/mrksntndr/Linear-Algebra-58019/blob/main/Python_Exercise3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([[4,10,8],[10,26,26],[8,26,61]])
B = np.array([[44],[128],[214]])

inv_A = np.linalg.inv(A)
x = np.linalg.inv(A).dot(B)

print(A)
print()
print(inv_A)
print()
print(B)
print()
print(x)

[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]

[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]

[[ 44]
 [128]
 [214]]

[[-8.]
 [ 6.]
 [ 2.]]
